### PR TITLE
Added Advanced Checkbox Hack

### PR DESCRIPTION
**Pull request by heiswayi**
Fixed sidebar-toggle animation problem on Android browser.

### CODE REVIEW

**Comment by mdo** [comment]
Adding that animation for everyone would probably be bad news for performance, no? I've seen far too many CPUs lose their cool with infinite animations.

**Comment by mafagafogigante** [comment]
All browsers have this issue with those versions of Android?
The comment could be shortened to reduce load time, but the greater impact is what mdo described above. I am against this mainly because I think that almost no one is affected.

Also because phone browsers suck want you or not, hate having to take them into consideration when Firefox and Chrome for desktops are so much more advanced and complete.

**Comment by heiswayi** [comment]
Yeap.. that hack can cause high CPU load.. I rarely use Chrome browser in my phone. I use CM browser. that's why I found the bug..

em perhaps, alternative to that if any? Using JavaScript maybe..

**Comment by heiswayi** [comment]
Yeap.. that's true. That CSS hack can cause high CPU load.

**Pull request closed without merging**
