### PR TITLE
Fetch font sheet over HTTPS

### PR DESCRIPTION
**Pull request by donmccurdy**
Was getting some warnings about loading insecure resources on an HTTPS site, easy enough to fix. :)

### CODE REVIEW

**Comment by maxammann** [comment]
Jup else it throws a warning and some browers maybe don't even load scripts from non https sites.

**Comment by nicolasmccurdy** [comment]
Maybe we should load this with `//` to support both HTTP and HTTPS sites.

`//fonts.googleapis.com/css?family=PT+Serif:400,400italic,700%7CPT+Sans:400`

**Comment by maxammann** [comment]
lol didn't know about this, but seems to be valid: http://stackoverflow.com/a/550073

**Comment by donmccurdy** [comment]
Easy to make the change either way of course, but HTTPS resources will definitely work correctly on HTTP sites. The problem is only when you try the other way around, because then a site *claiming* to be secure is trying to make non-secure requests, which most browsers block. There's a [blog post by Paul Irish on the subject](http://www.paulirish.com/2010/the-protocol-relative-url/), as well.

**Comment by nicolasmccurdy** [comment]
Interesting, I haven't thought about that. :+1: :smile:

**Pull request merged**
