### PR TITLE
Touch support for hiding sidebar

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes the touch-body-to-hide-sidebar interaction on iOS, I'll check on Android tomorrow.

### CODE REVIEW

**Comment by mdo** [comment]
What exactly does this fix?

**Comment by donmccurdy** [comment]
Oops, sorry yes my description was not very specific. On desktop, when the sidebar is open, clicking anywhere outside the sidebar will close it. Screenshot:

img_3163-01

I'd like to have the same behavior on mobile, but currently the only way to close the sidebar (at least on mobile Safari) is to press the menu button again.

This PR should fix that, although the `touchstart` event does seem to apply the :checked styling to the menu button twice (i.e. the styling appears, disappears, and then reappears after Safari's 300ms click debounce) so there may be a better approach to this.

**Comment by mdo** [comment]
Yeah, in the iOS simulator, this doesn't work quite right. Looks like it's reloading the page maybe.

**Comment by donmccurdy** [comment]
Alright, I'll look into this a bit more. I don't have quick access to Android or Windows Phone devices right at the moment, so I may wait a few weeks until I can test on those. Feel free to just close this in the meantime, if you'd prefer. Thanks!

**Comment by donmccurdy** [comment]
So this does seem to be working for me: I haven't been able to reproduce anything like reloading the page in the iOS simulator, I've tested there, my iOS phone, and an Android tablet. It's also enabled on my website ([donmccurdy.com](https://www.donmccurdy.com)). 

I did realize my original code wasn't quite right, since it wouldn't have listened for 'click' events on devices that have touch events _available_, which is bad if you're on a Surface or something and using a mouse. Changed that to bind two listeners instead, which is fine since only one will get past the `checkbox.checked` line.

A bit confused as to what causes the original issue: [this article about iOS's click event propagation](http://www.quirksmode.org/blog/archives/2010/09/click_event_del.html) seems like a candidate, but the issue appears on Android as well.

**Comment by mafagafogigante** [comment]
Just as a note: curious about this I went on and tested both my website (I'm pretty sure my tree does not have these commits) and yours on mobile IE (WP 8.1). Both work correctly (touching outside of the sidebar closes it).

**Pull request closed without merging**
