### PR TITLE
Package theme as a gem

### PR DESCRIPTION
**Pull request by DirtyF**
As of Jekyll 3.3, it's possible to ship theme as gems. 🎉 

Here's a 💎  version of Lanyon, following current default Jekyll's theme best practices to ship a theme.
## Changelog
- [x] Require Jekyll ~> 3.3
- [x] Rename `public` folder to `assets` to follow default convention
- [x] Refactor templates with new filters `relative_url` and `absolute_url`
- [x] handle feed with jekyll-feed
- [x] include jekyll-sitemap
- [x] include jekyll-paginate
- [x] Add an `example` folder for a demo usage
- [x] Add install instructions in the README
- [x] Publish gem on Rubygems as [jekyll-theme-lanyon](https://rubygems.org/gems/jekyll-theme-lanyon)

/cc @mdo

### CODE REVIEW

**Comment by sigul** [comment]
HI @DirtyF , how should this gem be used? I created a jeyll folder and gem install jekyll-theme-lanyon, added gems: [jekyll-theme-laynon] in config.yml but I wasn't able to run it because of dependencies. could you help setting up a jekyll lanyon site?

**Comment by DirtyF** [comment]
HI, @sigul you should add `theme: jekyll-theme-lanyon` on your `config.yml`. Let me know if you ran into issues.

**Comment by sigul** [comment]
I keep getting this error, even if I included gems: [jekyll-theme-lanyon] (and tried gems: [jekyll-theme-lanyon-1.0.0]) in the config: 

  Dependency Error: Yikes! It looks like you don't have jekyll-theme-lanyon or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-theme-lanyon' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

**Comment by DirtyF** [comment]
For those looking to use lanyon as a gem-based theme, [installation is documented](https://github.com/DirtyF/lanyon/blob/jekyll-theme/README.md#install-as-a-gem-based-theme).

**Pull request closed without merging**
