### PR TITLE
Fix sidebar toggle color

### PR DESCRIPTION
**Pull request by arjunsajeev**
#109 Remove gray color from sidebar toggle

### CODE REVIEW

**Comment by jholl** [comment]
#109

@arunjsajeev this doesn't address the `#555` background-image gradients in between the bars within the toggle.  that would require overrides for lines 230-250 (basically).

@mdo, are the theme colors moving to scss?  mixins would probably make this easy. let me know if I can help.

**Comment by shazamjad** [comment]
Less / scss would be awesome - for now I've just commented out the `background-image` and put a font-awesome icon (fa-bar) in the label.

**Comment by hbahamonde** [comment]
Hey @shazamjad, do you mind telling me which line should I comment on so as to delete the old hamburger icon? I managed to install the new "awesome" icon, but I couldn't remove the old icon, so I have two icons there. This is my website, so you can see it: http://hbahamonde.github.io. Thanks.

**Comment by hbahamonde** [comment]
I just fixed it. Just like @shazamjad said, I deleted the segments that contained `background-image` in the `lanyon.css` file. That is, I deleted segments `.sidebar-toggle:before` and `.sidebar-toggle:active:before`.

**Pull request closed without merging**
